export default {
  LOGIN: '/api/lawSystem/auth/login',
  TOKEN_EXPIRE: '/api/lawSystem/auth/tokenExpire',
  GET_RESOURCE_LIST: '/api/lawSystem/accountManage/getResourceList',
  GET_ROLE_LIST: '/api/lawSystem/accountManage/getRoleList',
  // 帐号管理
  GET_USER_LIST: '/api/lawSystem/accountManage/getUserList',
  ADD_USER: '/api/lawSystem/accountManage/addUser',
  DELETE_USER_BY_ID: '/api/lawSystem/accountManage/deleteUserById',
  GET_USER_BY_ID: '/api/lawSystem/accountManage/getUserById',
  EDIT_USER: '/api/lawSystem/accountManage/editUser',
  // 角色管理
  ADD_ROLE: '/api/lawSystem/accountManage/addRole',
  GET_ROLE_BY_ID: '/api/lawSystem/accountManage/getRoleById',
  EDIT_ROLE: '/api/lawSystem/accountManage/editRole',
  DELETE_ROLE_BY_ID: '/api/lawSystem/accountManage/deleteRoleById',
  // 班次
  GET_SCHEDULE_LIST: '/api/lawSystem/gateAlert/getScheduleList',
  ADD_SCHEDULE: '/api/lawSystem/gateAlert/addSchedule',
  GET_SCHEDULE_BY_ID: '/api/lawSystem/gateAlert/getScheduleById',
  EDIT_SCHEDULE: '/api/lawSystem/gateAlert/editSchedule',
  DELETE_SCHEDULE_BY_ID: '/api/lawSystem/gateAlert/deleteScheduleById',
  // 值班表
  GET_PLAN_DETAIL_LIST: '/api/slAirport/gateAlert/getPlanDetailList',
  GET_PLAN_WORKER_LIST: '/api/slAirport/gateAlert/getPlanWorkerList',
  // 车流量统计
  GET_VEHICLE_FLOW_COUNT: '/api/vehicleFlowCount/getVehicleFlowCount',
  GET_VEHICLE_FLOW_COUNT_EXCEL: '/api/vehicleFlowCount/getVehicleFlowCountExcel',
  // 重点关注
  GET_HUB_FOCUS_VEHICLE_LIST: '/api/transhub/fullscreen/getHubFocusVehicleList',
  GET_HUB_FOCUS_VEHICLE_EXCEL: '/api/transhub/fullscreen/getHubFocusVehicleExcel',
  GET_HUB_STAT_TRAIL_LIST: '/api/transhub/fullscreen/getHubStatTrailList',
  GET_HUB_STAT_TRAIL_ALL_EXCEL: '/api/transhub/fullscreen/getHubStatTrailAllExcel'
}
